COLORTERM=truecolor
COMMAND_MODE=unix2003
GIT_ASKPASS='/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh'
HOME=/Users/shikim
LANG=en_US.UTF-8
LOGNAME=shikim
LaunchInstanceID=016D608D-DF97-4C75-A20E-C5407A6C0250
MAIL=shikim@student.42seoul.kr
MallocNanoZone=0
OLDPWD=/Users/shikim/Documents/minishell
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
PATH=/Users/shikim/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/shikim/.brew/bin
PWD=/Users/shikim/Documents/minishell
SECURITYSESSIONID=186a6
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.oWgw9Zhgah/Listeners
TERM=xterm-256color
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.79.2
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000cz980037t_/T/
USER=shikim
USER_ZDOTDIR=/Users/shikim
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN='/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js'
VSCODE_GIT_ASKPASS_NODE='/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)'
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000cz980037t_/T/vscode-git-7b8a4a9e2b.sock
VSCODE_INJECTION=1
XPC_FLAGS=0x0
XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000001.Electron
ZDOTDIR=/Users/shikim
__CF_USER_TEXT_ENCODING=0x19F4A:0x0:0x0
a=''
